name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@master
      - run: deno upgrade
        continue-on-error: true
      - run: deno --version
      - run: deno run test/01.ts
      - run: deno test test/02.ts
      - run: deno run test/03.ts
