name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run: deno run test/01.ts
